### ISSUE TITLE
logicalSize and imageSize do nothing

### ISSUE THREAD

**Issue by alejandrogiubel** [Mohamedfaroouk/widget_to_marker#1]
Hi. logicalSize and imageSize do nothing. Looking in your code I can see that logicalSize and imageSize never be used. Will be nice resize the Bitmap generated. Thanks.

**Comment by Mohamedfaroouk** [comment]
Hi @alejandrogiubel

**Comment by Mohamedfaroouk** [comment]
Hi @alejandrogiubel 
thank you for telling me about the un used variables
I fixed it and publish  update for the package.
also you can resize the widget itself before converting using SizedBox
