### ISSUE TITLE
Can't change the size of a marker's image.

### ISSUE THREAD

**Issue by utkuvrs** [Mohamedfaroouk/widget_to_marker#10]
![image](https://github.com/Mohamedfaroouk/widget_to_marker/assets/98432874/aa65adb4-66d4-4c72-b6a0-b44a96adf5ed)

Can no longer control the size using the following:

Image(
        width: 40.w,
        height: 40.h,
        image: const AssetImage("assets/png/LocationPin.png"),
      );

                icon: await LocationPin(isActive: area.isActive)
                    .toBitmapDescriptor(
                  logicalSize: Size(40.w, 40.h),
                  imageSize: Size(40.w, 40.h),
                ),
                
 I've tried:
 
* to change the width & height on the Image params,
* to change the logicalSize & imageSize (and separately)

Nothing seems to change/effect the size/width/height of the marker's image.

**Comment by utkuvrs** [comment]
![ActiveLocationPin](https://github.com/Mohamedfaroouk/widget_to_marker/assets/98432874/17c15085-1c74-4bf9-be63-de0228649dfc)
Here is the ActiveLocationPin that I'm using as an asset.

**Comment by Mohamedfaroouk** [comment]
Logical Size:

Definition: Logical size represents the size of the widget in logical pixels. Logical pixels are an abstract unit that Flutter uses to describe the layout dimensions in a device-independent manner.

Image Size:

Definition: Image size refers to the size of the final rendered image in physical pixels. Physical pixels are the actual pixels on the screen, and the density of these pixels can vary between different devices.


Practical Example:
Suppose the device has a DPR of 2.0.
If logicalSize is 200x100 logical pixels, imageSize should ideally be 400x200 physical pixels (2002 by 1002) to maintain the same aspect ratio and render a clear image.
