### ISSUE TITLE
Can not control size

### ISSUE THREAD

**Issue by hdhaheri** [Mohamedfaroouk/widget_to_marker#6]
Thank you for the widget. The marker image and text appear very big. Using logicalSize or the image size inside the widget does not change anything. Am I missing anything? I've used the example in repo.
Thanks

**Comment by Mohamedfaroouk** [comment]
@hdhaheri  make sure that u use the last version 1.0.4
also u shlould consider the percentage between logical and image size but
u also can wrap your widget with sizedbox  and give it the size u want
