### ISSUE TITLE
Network image issue

### ISSUE THREAD

**Issue by KuldeepChauahan** [Mohamedfaroouk/widget_to_marker#8]
when i add Network image it will not showing at initial state but when i change tab from bottomNavBar then image will show is any one have solution of it ?

**Comment by Mohamedfaroouk** [comment]
network image need sometime to get the image before render it so you need to increese the waitToRender attrbute

**Comment by Sklyvan** [comment]
I recommend to everyone having this issue to preload the image to cache before converting to Bitmap Descripton:
```dart
await precacheImage(NetworkImage(imageURL));
marker.toBitmapDescriptor();
. . . 
```
